% This file is autogenerated by routes_gen. Do not edit because your edit will
% be lost when this file is regenerated.
-module(routes).

-export([route_uri/2, route_tokens/2]).

route_uri(Method, Uri) -> Tokens = string:tokens(Uri, "/"), route_tokens(Method, Tokens).

% controller_articles
run_tokens(get, ["articles"]) -> apply(controller_articles, index, []);
run_tokens(get, ["articles", Id]) -> apply(controller_articles, show, [Id]);
run_tokens(get, ["articles", "new"]) -> apply(controller_articles, new, []);
run_tokens(post, ["articles"]) -> apply(controller_articles, create, []);
run_tokens(get, ["articles", Id, "edit"]) -> apply(controller_articles, edit, [Id]);
run_tokens(put, ["articles", Id]) -> apply(controller_articles, update, [Id]);
run_tokens(delete, ["articles", Id]) -> apply(controller_articles, delete, [Id]);

% controller_content
run_tokens(get, []) -> apply(controller_content, recent_contents, []);

route_tokens(_, _) -> no_controller_and_action.
